require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CarriersController do

  # This should return the minimal set of attributes required to create a valid
  # Carrier. As you add validations to Carrier, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CarriersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all carriers as @carriers" do
      carrier = Carrier.create! valid_attributes
      get :index, {}, valid_session
      assigns(:carriers).should eq([carrier])
    end
  end

  describe "GET show" do
    it "assigns the requested carrier as @carrier" do
      carrier = Carrier.create! valid_attributes
      get :show, {:id => carrier.to_param}, valid_session
      assigns(:carrier).should eq(carrier)
    end
  end

  describe "GET new" do
    it "assigns a new carrier as @carrier" do
      get :new, {}, valid_session
      assigns(:carrier).should be_a_new(Carrier)
    end
  end

  describe "GET edit" do
    it "assigns the requested carrier as @carrier" do
      carrier = Carrier.create! valid_attributes
      get :edit, {:id => carrier.to_param}, valid_session
      assigns(:carrier).should eq(carrier)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Carrier" do
        expect {
          post :create, {:carrier => valid_attributes}, valid_session
        }.to change(Carrier, :count).by(1)
      end

      it "assigns a newly created carrier as @carrier" do
        post :create, {:carrier => valid_attributes}, valid_session
        assigns(:carrier).should be_a(Carrier)
        assigns(:carrier).should be_persisted
      end

      it "redirects to the created carrier" do
        post :create, {:carrier => valid_attributes}, valid_session
        response.should redirect_to(Carrier.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved carrier as @carrier" do
        # Trigger the behavior that occurs when invalid params are submitted
        Carrier.any_instance.stub(:save).and_return(false)
        post :create, {:carrier => {}}, valid_session
        assigns(:carrier).should be_a_new(Carrier)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Carrier.any_instance.stub(:save).and_return(false)
        post :create, {:carrier => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested carrier" do
        carrier = Carrier.create! valid_attributes
        # Assuming there are no other carriers in the database, this
        # specifies that the Carrier created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Carrier.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => carrier.to_param, :carrier => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested carrier as @carrier" do
        carrier = Carrier.create! valid_attributes
        put :update, {:id => carrier.to_param, :carrier => valid_attributes}, valid_session
        assigns(:carrier).should eq(carrier)
      end

      it "redirects to the carrier" do
        carrier = Carrier.create! valid_attributes
        put :update, {:id => carrier.to_param, :carrier => valid_attributes}, valid_session
        response.should redirect_to(carrier)
      end
    end

    describe "with invalid params" do
      it "assigns the carrier as @carrier" do
        carrier = Carrier.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Carrier.any_instance.stub(:save).and_return(false)
        put :update, {:id => carrier.to_param, :carrier => {}}, valid_session
        assigns(:carrier).should eq(carrier)
      end

      it "re-renders the 'edit' template" do
        carrier = Carrier.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Carrier.any_instance.stub(:save).and_return(false)
        put :update, {:id => carrier.to_param, :carrier => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested carrier" do
      carrier = Carrier.create! valid_attributes
      expect {
        delete :destroy, {:id => carrier.to_param}, valid_session
      }.to change(Carrier, :count).by(-1)
    end

    it "redirects to the carriers list" do
      carrier = Carrier.create! valid_attributes
      delete :destroy, {:id => carrier.to_param}, valid_session
      response.should redirect_to(carriers_url)
    end
  end

end
